### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by saniko** [sfrpl/rasa-chatbot#1]
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 61)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 61))

**Comment by sfrpl** [comment]
You can delete that entry from requirements.txt and try again

**Comment by oldmonkABA** [comment]
have deleted the line from requirements.txt .. Get back in case of any further issues. Closing this
